version: '3.8'

services:
  # Databases
  mongo:
    image: mongo:6.0
    container_name: fh-mongo
    ports: ['27017:27017']
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: fh-redis
    ports: ['6379:6379']

  minio:
    image: minio/minio:RELEASE.2025-01-01T00-00-00Z
    container_name: fh-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    ports: ['9000:9000']
    volumes:
      - minio-data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: fh-rabbit
    ports: ['5672:5672', '15672:15672']

  # Kong DB
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    volumes:
      - kong-db-data:/var/lib/postgresql/data

  # Kong Gateway
  kong:
    image: kong:3.6
    container_name: kong
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
    ports:
      - "8000:8000"   # Public Gateway
      - "8443:8443"   # TLS Gateway
      - "8001:8001"   # Admin API
      - "8444:8444"   # Admin TLS
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml

  # Microservices
  auth-rs:
    build: ../../apps/auth-rs
    container_name: fh-auth
    env_file: ../../config/.env
    ports: ['8080:8080']
    depends_on: [mongo]

  phishing-rs:
    build: ../../apps/phishing-rs
    container_name: fh-phishing
    env_file: ../../config/.env
    ports: ['8081:8081']
    depends_on: [rabbitmq, redis]

  malware-rs:
    build: ../../apps/malware-rs
    container_name: fh-malware
    env_file: ../../config/.env
    ports: ['8082:8082']
    depends_on: [rabbitmq, mongo]

  history-ts:
    build: ../../apps/history-ts
    container_name: fh-history
    env_file: ../../config/.env
    ports: ['8083:8083']
    depends_on: [mongo]

  report-go:
    build: ../../apps/report-go
    container_name: fh-report
    env_file: ../../config/.env
    ports: ['8084:8084']
    depends_on: [mongo, minio, rabbitmq]
    volumes:
      - ../../apps/report-go/reports:/app/reports

  notify-py:
    build: ../../apps/notify-py
    container_name: fh-notify
    env_file: ../../config/.env
    ports: ['8085:8085']
    depends_on: [rabbitmq]

volumes:
  mongo-data:
  minio-data:
  kong-db-data:
