_format_version: "3.0"

services:
  - name: auth-service
    host: auth-rs
    port: 8080
    protocol: http
    routes:
      - name: auth-route
        paths:
          - "/auth"
        strip_path: true

  - name: phishing-service
    host: phishing-rs
    port: 8081
    protocol: http
    routes:
      - name: phishing-route
        paths:
          - "/scan/url"
        strip_path: true

  - name: malware-service
    host: malware-rs
    port: 8082
    protocol: http
    routes:
      - name: malware-route
        paths:
          - "/scan/file"
        strip_path: true

  - name: history-service
    host: history-ts
    port: 8083
    protocol: http
    routes:
      - name: history-route
        paths:
          - "/history"
        strip_path: true

  - name: report-service
    host: report-go
    port: 8084
    protocol: http
    routes:
      - name: report-route
        paths:
          - "/reports"
        strip_path: true

  - name: notify-service
    host: notify-py
    port: 8085
    protocol: http
    routes:
      - name: notify-route
        paths:
          - "/notifications"
        strip_path: true

plugins:
  - name: cors
    config:
      origins: ["http://localhost:5173"]
      methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      headers: ["Authorization", "Content-Type"]
      credentials: true
      max_age: 3600